In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
%matplotlib inline
mpl.style.use('ggplot')

In [2]:
meta= pd.read_csv('Metalearning.csv')

In [3]:
meta.head()

Atomic Radius(Atomic unit)  Expansion Coefficient  Electron Affinity(-ive)  \
0                        1.20                  0.000                       73   
1                        1.32                  0.006                       17   
2                        1.33                  0.008                       16   
3                        1.34                  0.008                       16   
4                        1.32                  0.008                       16   

   Conductivity  Yield Strength  Outcome  
0          1.20     1213.355372        2  
1         21.84      136.809524        1  
2         28.14      179.362319        1  
3         55.20       57.607167        1  
4         47.76       59.913043        1

In [4]:
meta.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2019 entries, 0 to 2018
Data columns (total 6 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   Atomic Radius(Atomic unit)  2019 non-null   float64
 1   Expansion Coefficient       2019 non-null   float64
 2   Electron Affinity(-ive)     2019 non-null   int64  
 3   Conductivity                2019 non-null   float64
 4   Yield Strength              2019 non-null   float64
 5   Outcome                     2019 non-null   int64  
dtypes: float64(4), int64(2)
memory usage: 94.8 KB


In [5]:
meta['Atomic Radius(Atomic unit)'].unique()

array([1.2 , 1.32, 1.33, 1.34, 1.22, 1.51, 1.5 , 1.31, 1.3 , 1.29, 1.28,
       1.24, 1.15, 1.14, 1.16, 1.58, 1.56, 1.48, 1.49, 1.46, 1.44, 1.36,
       1.41, 1.38, 1.4 , 1.54, 1.45, 1.39, 1.25, 1.23, 1.59, 1.43, 1.19,
       1.21, 1.27, 1.26, 1.18, 1.42, 1.35, 1.37, 1.47, 1.57, 1.17, 1.52,
       1.12, 1.06, 1.1 , 1.6 ])

In [6]:
meta['Expansion Coefficient'].unique()

array([0.   , 0.006, 0.008, 0.01 , 0.013, 0.003, 0.001, 0.004, 0.005,
       0.002, 0.007, 0.009, 0.012, 0.011, 0.015, 0.014])

In [7]:
meta['Electron Affinity(-ive)'].unique()

array([73, 17, 16, 26, 29, 86, 64, 28, 21, 19, 24, 18, 23, 30, 34, 22, 27,
       40, 20, 43, 61, 70, 57, 58, 39, 41, 33, 25, 44, 46, 45, 53, 52, 56,
       65, 36, 35, 38, 62, 51, 67, 68, 63, 60, 47, 50, 54, 48, 55, 31, 32,
       37, 49, 66, 14, 12, 13, 74, 75, 72, 77, 71, 69, 76, 79, 84, 78, 81,
       59, 42, 83, 80, 15], dtype=int64)

In [8]:
meta['Conductivity'].unique()

array([1.2000e+00, 2.1840e+01, 2.8140e+01, 5.5200e+01, 4.7760e+01,
       0.0000e+00, 3.1800e+00, 5.2440e+01, 5.9000e+01, 1.8060e+01,
       8.1000e+00, 1.8170e+01, 2.0010e+01, 2.2890e+01, 3.3360e+01,
       1.6720e+01, 1.3260e+01, 1.7850e+01, 1.1390e+01, 1.0000e+01,
       1.9200e+00, 4.6200e+01, 3.0000e+01, 5.6250e+01, 4.3470e+01,
       4.3790e+01, 7.3780e+01, 3.9680e+01, 8.9540e+01, 6.3920e+01,
       5.1840e+01, 7.0560e+01, 2.8520e+01, 2.6840e+01, 3.2400e+01,
       2.1280e+01, 2.0520e+01, 6.6880e+01, 7.3790e+01, 1.0829e+02,
       1.0550e+02, 1.1620e+02, 2.5330e+01, 1.6640e+01, 9.1020e+01,
       1.7820e+01, 3.1000e+00, 1.5300e+00, 1.5360e+01, 1.7160e+01,
       4.4000e+00, 5.1200e+00, 6.8200e+00, 4.6800e+00, 4.1600e+00,
       1.6800e+01, 2.0100e+01, 4.5600e+00, 1.1900e+01, 1.2360e+01,
       1.0400e+01, 9.2000e+00, 1.9350e+01, 3.3630e+01, 2.2650e+01,
       1.2060e+01, 1.9040e+01, 3.7910e+01, 4.0470e+01, 4.4030e+01,
       2.5760e+01, 1.8960e+01, 1.2540e+01, 1.3200e+00, 4.2120e

In [16]:
meta['Yield Strength'].unique()

array([1213.355372  ,  136.8095238 ,  179.3623188 , ...,   45.40131579,
         37.51655629,   33.88965517])

In [11]:
meta

Atomic Radius(Atomic unit)  Expansion Coefficient  \
0                           1.20                  0.000   
1                           1.32                  0.006   
2                           1.33                  0.008   
3                           1.34                  0.008   
4                           1.32                  0.008   
...                          ...                    ...   
2014                        1.40                  0.007   
2015                        1.40                  0.007   
2016                        1.40                  0.007   
2017                        1.40                  0.006   
2018                        1.42                  0.008   

      Electron Affinity(-ive)  Conductivity  Yield Strength  Outcome  
0                          73          1.20     1213.355372        2  
1                          17         21.84      136.809524        1  
2                          16         28.14      179.362319        1  
3                          16         55.20       57.607167        1  
4                          16         47.76       59.913043        1  
...                       ...           ...             ...      ...  
2014                       79          1.44       27.039474        2  
2015                       78          2.84       30.013245        2  
2016                       79          2.44       45.401316        2  
2017                       78          2.80       37.516556        2  
2018                       74          2.00       33.889655        1  

[2019 rows x 6 columns]

In [12]:
meta['Yield Strength']=meta['Yield Strength'].astype(float)

In [13]:
meta.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2019 entries, 0 to 2018
Data columns (total 6 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   Atomic Radius(Atomic unit)  2019 non-null   float64
 1   Expansion Coefficient       2019 non-null   float64
 2   Electron Affinity(-ive)     2019 non-null   int64  
 3   Conductivity                2019 non-null   float64
 4   Yield Strength              2019 non-null   float64
 5   Outcome                     2019 non-null   int64  
dtypes: float64(4), int64(2)
memory usage: 94.8 KB


In [14]:
meta.describe()

Atomic Radius(Atomic unit)  Expansion Coefficient  \
count                 2019.000000            2019.000000   
mean                     1.331238               0.004415   
std                      0.095920               0.002948   
min                      1.060000               0.000000   
25%                      1.260000               0.002000   
50%                      1.330000               0.005000   
75%                      1.400000               0.007000   
max                      1.600000               0.015000   

       Electron Affinity(-ive)  Conductivity  Yield Strength      Outcome  
count              2019.000000   2019.000000     2019.000000  2019.000000  
mean                 46.737989     11.530466      232.932015     1.292719  
std                  17.083286     15.951390      361.172830     0.605559  
min                  12.000000      0.000000        2.933824     1.000000  
25%                  32.000000      3.180000       43.746032     1.000000  
50%                  48.000000      7.080000      113.192593     1.000000  
75%                  61.000000     13.690000      266.008306     1.000000  
max                  86.000000    187.590000     3826.644295     3.000000

In [17]:
meta.to_csv('Cleaned Metalearning.csv')

### MODEL

In [18]:
x=meta.drop(columns='Outcome')
y=meta['Outcome']

In [19]:
x

Atomic Radius(Atomic unit)  Expansion Coefficient  \
0                           1.20                  0.000   
1                           1.32                  0.006   
2                           1.33                  0.008   
3                           1.34                  0.008   
4                           1.32                  0.008   
...                          ...                    ...   
2014                        1.40                  0.007   
2015                        1.40                  0.007   
2016                        1.40                  0.007   
2017                        1.40                  0.006   
2018                        1.42                  0.008   

      Electron Affinity(-ive)  Conductivity  Yield Strength  
0                          73          1.20     1213.355372  
1                          17         21.84      136.809524  
2                          16         28.14      179.362319  
3                          16         55.20       57.607167  
4                          16         47.76       59.913043  
...                       ...           ...             ...  
2014                       79          1.44       27.039474  
2015                       78          2.84       30.013245  
2016                       79          2.44       45.401316  
2017                       78          2.80       37.516556  
2018                       74          2.00       33.889655  

[2019 rows x 5 columns]

In [20]:
y

0       2
1       1
2       1
3       1
4       1
       ..
2014    2
2015    2
2016    2
2017    2
2018    1
Name: Outcome, Length: 2019, dtype: int64

### Applying Test train split

In [21]:
from sklearn.model_selection import train_test_split
x_train,x_test, y_train,y_test=train_test_split(x,y,test_size=0.2)

In [29]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import make_pipeline
from sklearn.pipeline import Pipeline
from sklearn.metrics import r2_score


In [30]:
ohe=OneHotEncoder()
ohe.fit(x[['Atomic Radius(Atomic unit)','Expansion Coefficient','Electron Affinity(-ive)','Conductivity','Yield Strength']])

OneHotEncoder()

In [31]:
column_trans=make_column_transformer((OneHotEncoder(categories=ohe.categories_),['Atomic Radius(Atomic unit)','Expansion Coefficient','Electron Affinity(-ive)','Conductivity','Yield Strength']),
                                    remainder='passthrough')

In [32]:
lr=LinearRegression()

In [33]:
pipe=make_pipeline(column_trans,lr)

In [34]:
pipe.fit(x_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array([1.06, 1.1 , 1.12, 1.14, 1.15, 1.16, 1.17, 1.18, 1.19, 1.2 , 1.21,
       1.22, 1.23, 1.24, 1.25, 1.26, 1.27, 1.28, 1.29, 1.3 , 1.31, 1.32,
       1.33, 1.34, 1.35, 1.36, 1.37, 1.38, 1.39, 1.4 , 1.41, 1.42, 1.43,
       1.44, 1.45, 1.46, 1.47, 1.48, 1.49, 1.5 , 1.51, 1.52, 1....
       1.0701e+02, 1.0783e+02, 1.0829e+02, 1.1620e+02, 1.1832e+02,
       1.3376e+02, 1.4650e+02, 1.6872e+02, 1.8738e+02, 1.8759e+02]),
                                                                            array([2.93382353e+00, 3.45198676e+00, 4.32000000e+00, ...,
       3.18864000e+03, 3.63318584e+03, 3.82664430e+03])]),
                                                  ['Atomic Radius(Atomic unit)',
                                                   'Expansion

In [35]:
y_pred= pipe.predict(x_test)

In [36]:
r2_score(y_test,y_pred)

0.45528201918077116

In [40]:

for i in range(1000):
    x_train,x_test, y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=i)
    lr=LinearRegression()
    pipe=make_pipeline(column_trans,lr)
    pipe.fit(x_train,y_train)
    y_pred= pipe.predict(x_test)
    print(r2_score(y_test,y_pred),i)

0.3790083940908422 0
0.3090571334576392 1
0.3766478315913929 2
0.3790250833288161 3
0.44429685628255733 4
0.36708658947828077 5
0.3440360760849426 6
0.4619195482358359 7
0.3843537003434895 8
0.33417321518657706 9
0.3849222187703307 10
0.48019291682180987 11
0.4021027350197348 12
0.37713090293362417 13
0.41525162770241464 14
0.392402602503622 15
0.35812156322253497 16
0.3243177993947527 17
0.4532940881538611 18
0.43436226410334877 19
0.30663402028242204 20
0.42890159225069624 21
0.43090094670671697 22
0.40480102761958703 23
0.3455187486449689 24
0.346482506477095 25
0.35377981327512764 26
0.29230849361679934 27
0.31068554680998206 28
0.31121951773369394 29
0.33279999436485186 30
0.37933154564689653 31
0.3647643331338989 32
0.3666613048021907 33
0.4056187657898376 34
0.38083200447803245 35
0.3872969615024361 36
0.4248388930421698 37
0.36630400058158497 38
0.3920316971346509 39
0.35507038553528114 40
0.35762083238807885 41
0.3483626682956662 42
0.35849266419823 43
0.4185600682887701 44
0.

0.315892642565206 358
0.4253256114775176 359
0.33628051673064974 360
0.3436817224839357 361
0.48274818069219616 362
0.3906414025615561 363
0.30339208444687626 364
0.4199723112217528 365
0.4233218773570099 366
0.4551555482082279 367
0.2934576795375161 368
0.23685138363071112 369
0.3806423557626424 370
0.3914179591663214 371
0.4322498155233696 372
0.3144279657885073 373
0.38369326371455714 374
0.42873673001624923 375
0.4840048565887497 376
0.4363080651053586 377
0.3974785179303024 378
0.3921796904541117 379
0.4117444504607819 380
0.32085166570144896 381
0.43806888616074 382
0.452019276390383 383
0.377817205886956 384
0.38104507831195267 385
0.37319788978573987 386
0.33750331840820114 387
0.3763388869150336 388
0.50447987051254 389
0.3728584584688158 390
0.4328962798591439 391
0.3908937136838745 392
0.36961718159125345 393
0.3853747484483684 394
0.43198393270452184 395
0.35095446311695 396
0.3280799712916792 397
0.3828534619116907 398
0.5471018718541678 399
0.459717031199371 400
0.3600229

0.31391873192529374 711
0.4409161557386738 712
0.47374349328853005 713
0.40194648892206575 714
0.4190317414445378 715
0.35352787718198864 716
0.322368776260222 717
0.37911350321628556 718
0.3588929315267977 719
0.43455248457374074 720
0.36870866611815933 721
0.4269673150244153 722
0.32417440676521825 723
0.26851990056016095 724
0.43816471448194527 725
0.40207197113803206 726
0.3879279319635418 727
0.45305149757937424 728
0.3558900172382138 729
0.3504405241301183 730
0.4408907996810556 731
0.33908520786385754 732
0.3772144240093065 733
0.44905842169075294 734
0.2972116529925479 735
0.2854745645578973 736
0.3357650898736596 737
0.40355043793495016 738
0.3700885591144629 739
0.39678087640501936 740
0.3717356470085892 741
0.3474872362113375 742
0.4449599017195508 743
0.37199066017376115 744
0.4488194813502112 745
0.2996084420462609 746
0.4787294559240288 747
0.4308794409923504 748
0.3511915223778195 749
0.3769551360980665 750
0.361127178524394 751
0.39614690830769217 752
0.4031542850319349

In [37]:
scores=[]
for i in range(1000):
    x_train,x_test, y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=i)
    lr=LinearRegression()
    pipe=make_pipeline(column_trans,lr)
    pipe.fit(x_train,y_train)
    y_pred= pipe.predict(x_test)
    scores.append(r2_score(y_test,y_pred))

In [38]:
np.argmax(scores)

399

In [39]:
scores[np.argmax(scores)]

0.5471018718541678

In [41]:
pipe.predict(pd.DataFrame(columns=x_test.columns,data=np.array([1.2,0.0,73,1.2,1213.355372]).reshape(1,5)))

array([2.00000066])